In [1]:
import numpy as np

In [10]:
starts = np.array([(2,0), (0,0), (1,0), (3,0), (4,0), (5,0), (0, 4), (3,4), (0,7), (2,7)])
starts = np.array([(2,0,1,3,4,5,0,3,0,2), (0,0,0,0,0,0,4,4,7,7)])
starts.shape

(2, 10)

In [12]:
np.ravel_multi_index(starts,(6,8))

array([16,  0,  8, 24, 32, 40,  4, 28,  7, 23])

In [2]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [16]:
np.save(

array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]],



       [[[[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]],


        [[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]]])

In [15]:
b[c,1]

array([ 1,  8, 15, 22])

In [21]:
c = np.arange(4)
d = np.ravel_multi_index(c,(4,4,4,4))
d

27

In [1]:
state_prime = {'distance':(80,80), 'ball_direction':(1,-1), 'fire':0}
state_prime

{'distance': (80, 80), 'ball_direction': (1, -1), 'fire': 0}

In [2]:
a, b = state_prime['ball_direction']
a, b

(1, -1)

In [26]:
import numpy as np
action = np.arange(6)
action

array([0, 1, 2, 3, 4, 5])

In [24]:
action[np.nonzero(action==2)] = -1
action

array([ 6,  5,  4,  3, -1,  1])

In [21]:
np.argwhere(action==2).shape

(1, 1)

In [27]:
for i in range(action.shape[0]):
    if action[i]==2 or action[i]==4:
        action[i]=-1
    if action[i]==3 or action[i]==5:
        action[i]=1
    if action[i]==0 or action[i]==1:
        action[i]=10
action

array([10, 10, -1, 10, -1, 10])